name: Blackberry Hill Farm
favicon: null
layout_spectrum: 0.7155857246834785
typography_spectrum: 0.9932945782784373
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#88c9ff'
    - '#fefefe'
    - '#212322'
    - '#af9447'
    - '#3c5e8c'
  brandStrength: 0.5
  lightness: 0.5565667354967445
  saturation: 1
  rhythmicContrast: 0.08014462422579527
purpose: []
